apiVersion: v1
kind: ConfigMap
metadata:
  name: qrcode-config
  namespace: default
data:
  DATABASE_URL: "postgresql://postgres:postgres@qrcode-postgres-service:5432/qrcode_db"
  AWS_ENDPOINT_URL: "http://qrcode-localstack-service:4566"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_S3_BUCKET_NAME: "qrcode-bucket"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://qrcode-jaeger-service:4317"
  OTEL_SERVICE_NAME: "qrcode-generator-service"
