apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qrcode-generator-gitops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # URL of the student's GitHub repository containing this codebase
    repoURL: 'https://github.com/sevvalculcu/bulutproje.git'
    targetRevision: HEAD
    path: helm/qrcode-generator
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
