apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qrcode-generator.fullname" . }}-config
  labels:
    {{- include "qrcode-generator.labels" . | nindent 4 }}
data:
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ include "qrcode-generator.fullname" . }}-postgres-service:5432/{{ .Values.postgres.database }}"
  AWS_ENDPOINT_URL: "http://{{ include "qrcode-generator.fullname" . }}-localstack-service:4566"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_S3_BUCKET_NAME: "qrcode-bucket"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://{{ include "qrcode-generator.fullname" . }}-jaeger-service:4317"
  OTEL_SERVICE_NAME: "{{ include "qrcode-generator.fullname" . }}"
